# Generated by Django 2.1.5 on 2019-02-05 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundooapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestRegistration',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
