# Generated by Django 2.1.5 on 2019-02-11 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundooapp', '0002_auto_20190205_0725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
